name: ci

on: push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Download Repository
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.14.2

            - name: Install Poetry with pip
              run: pip install poetry

            - name: Instalar dependencies with poetry
              run: poetry install

            - name: Run my test routine with Poetry
              run: poetry run python -m pytest tests -v